//>>built
define("net/apachegui/AutoSuggest","dojo/_base/declare dojo/dom dojo/dom-style dojo/request/script dojo/on dojo/keys dojo/dom-class dojo/query dojo/dom-attr dojo/mouse dojo/_base/event dojo/_base/fx".split(" "),function(q,l,d,r,e,g,h,m,n,s,k,t){return q(null,{initialized:!1,isShown:!1,isHoverShown:!1,onSelect:null,onShow:null,onHide:null,selectedItem:-1,hoverEnabled:!0,hoverContainer:null,hoverClass:null,hoverOutTimer:"",moveAutoSuggestContainerHandle:null,moveBodyHandle:null,constructor:function(a){var b=
this;this.hoverContainer=a.hoverContainer||document.body;this.hoverClass=a.hoverClass||null;this.onSelect=a.onSelect||function(){};this.onHighlight=a.onHighlight||function(){};this.onShow=a.onShow||function(){};this.onHide=a.onHide||function(){};this.onShowHover=a.onShowHover||function(){};this.onHideHover=a.onHideHover||function(){};this.id=0;net.apachegui.AutoSuggest?this.initialized=!0:net.apachegui.Main.getInstance().getApacheVersion(function(a){a="/ApacheGUI/manual/auto_suggest_"+a.replace(".",
"")+".min.js";r.get(a).then(function(){b.initialized=!0})});this.addToPage();this.addListeners()},getAutoSuggestContainer:function(){return l.byId(this.id+"-autoSuggestContainer")},getAutoSuggestKeywordContainer:function(){return l.byId(this.id+"-autoSuggestKeywordContainer")},getAutoSuggestDescriptionContainer:function(){return l.byId(this.id+"-autoSuggestDescriptionContainer")},getAutoSuggestKeywordList:function(){return l.byId(this.id+"-autoSuggestKeywordList")},addToPage:function(){this.id=m(".autoSuggestContainer").length;
var a=document.createElement("div");a.id=this.id+"-autoSuggestContainer";h.add(a,"autoSuggestContainer");d.set(a,"display","none");a.innerHTML='\x3cdiv class\x3d"autoSuggestKeywordContainer" id\x3d"'+this.id+'-autoSuggestKeywordContainer"\x3e\x3cul class\x3d"autoSuggestKeywordList" id\x3d"'+this.id+'-autoSuggestKeywordList"\x3e\x3c/ul\x3e\x3c/div\x3e\x3cdiv class\x3d"autoSuggestDescriptionContainer" id\x3d"'+this.id+'-autoSuggestDescriptionContainer"\x3e\x3c/div\x3e';document.body.appendChild(a)},
show:function(a,b){this.isShown||(d.set(this.getAutoSuggestKeywordContainer(),"display","inline-block"),d.set(this.getAutoSuggestContainer(),"display","block"),this.updatePosition(a,b),this.onShow(),this.isShown=!0);this.highlightItem(0);this.updatePosition(a,b)},hide:function(){this.isShown&&(d.set(this.getAutoSuggestContainer(),"display","none"),this.onHide(),this.isShown=!1)},showHover:function(a,b,c){a=a.replace("\x3c","").replace("\x26lt;","");!this.isHoverShown&&this.buildDescriptionContainer(a)&&
(this.updatePosition(b,c),d.set(this.getAutoSuggestKeywordContainer(),"display","none"),a=this.getAutoSuggestContainer(),d.set(a,"opacity","0"),d.set(a,"display","block"),t.fadeIn({node:a}).play(),h.add(this.getAutoSuggestDescriptionContainer(),"hover_state"),this.addHoverEvents(),this.onShowHover(),this.isHoverShown=!0)},clearHoverOutTimeout:function(){""!=this.hoverOutTimer&&(clearTimeout(this.hoverOutTimer),this.hoverOutTimer="")},addHoverEvents:function(){var a=this;this.hoverOutTimer="";this.moveAutoSuggestContainerHandle=
e(this.getAutoSuggestContainer(),"mousemove",function(b){a.clearHoverOutTimeout();b.stopPropagation()});this.moveBodyHandle=e(document.body,"mousemove",function(){""==a.hoverOutTimer&&(a.hoverOutTimer=setTimeout(function(){a.hideHover()},700))})},removeHoverEvents:function(){this.clearHoverOutTimeout();this.moveAutoSuggestContainerHandle&&this.moveAutoSuggestContainerHandle.remove();this.moveBodyHandle&&this.moveBodyHandle.remove()},hideHover:function(){this.isHoverShown&&(d.set(this.getAutoSuggestContainer(),
"display","none"),h.remove(this.getAutoSuggestDescriptionContainer(),"hover_state"),this.removeHoverEvents(),this.onHideHover(),this.isHoverShown=!1)},enableHover:function(){this.hoverEnabled=!0},disableHover:function(){this.hoverEnabled=!1},hideAll:function(){this.hideHover();this.hide()},updatePosition:function(a,b){var c=this.getAutoSuggestContainer(),f=window.innerHeight;f/2>b?(d.set(c,"bottom","auto"),d.set(c,"top",b+"px")):(d.set(c,"top","auto"),d.set(c,"bottom",f-b+"px"));var f=window.innerWidth,
p=this.getAutoSuggestKeywordContainer().offsetWidth,e=-10;f/2>a?(d.set(c,"left",a+"px"),d.set(c,"right","auto"),e+=f-a-p):(d.set(c,"left","auto"),d.set(c,"right",f-a+"px"),e+=f-(f-a)-p);d.set(this.getAutoSuggestDescriptionContainer(),"max-width",e+"px")},getKeywordListItems:function(){return m("li",this.getAutoSuggestKeywordList())},getNameFromListItem:function(a){return n.get(a,"data-value")},highlightItem:function(a){var b=this.getKeywordListItems();a<b.length&&0<=a&&(this.selectedItem=a,b.removeClass("selected"),
h.add(b[a],"selected"),a=this.getNameFromListItem(b[a]).toLowerCase(),this.buildDescriptionContainer(a),this.onHighlight(a))},getItemFromName:function(a){a=a.toLowerCase();var b=net.apachegui.AutoSuggest.DIRECTIVES[a];"undefined"==typeof b&&(b=net.apachegui.AutoSuggest.ENCLOSURES[a]);return b},buildDescriptionContainer:function(a){if(a=this.getItemFromName(a)){for(var b=a.items,c='\x3cdiv"\x3e\x3cdiv class\x3d"header"\x3e'+a.name+"\x3c/div\x3e\x3ctable\x3e",d=0;d<b.length;d++)c+='\x3ctr\x3e\x3ctd class\x3d"name"\x3e'+
b[d].name+'\x3c/td\x3e\x3ctd class\x3d"value"\x3e'+b[d].value+"\x3c/td\x3e\x3c/tr\x3e";c+='\x3c/table\x3e\x3cp class\x3d"manual_link"\x3e\x3ca href\x3d"'+a.href+'" target\x3d"_blank"\x3eFull Description\x3c/a\x3e\x3c/p\x3e\x3c/div\x3e';this.getAutoSuggestDescriptionContainer().innerHTML=c;return!0}return!1},selectItem:function(a){a=this.getKeywordListItems()[a];a=this.getNameFromListItem(a);this.onSelect(a);this.hide()},buildKeywordList:function(a){for(var b="",c=0;c<a.length;c++)b+='\x3cli data-index\x3d"'+
c+'" data-value\x3d"'+a[c]+'"\x3e'+a[c]+"\x3c/li\x3e";return b},updateSuggestions:function(a,b,c,d){if(this.initialized){this.selectedItem=-1;var e=null;if(a.length==b||a.length>b&&/\s/m.test(a[b]))a=a.substring(0,b),/^(\s*\w+)$/m.test(a)&&(e=net.apachegui.AutoSuggest.DIRECTIVETREE),/^(\s*<\s*\w+)$/m.test(a)&&(e=net.apachegui.AutoSuggest.ENCLOSURETREE);if(e){a=a.trim().toLowerCase().replace("\x3c","");for(b=0;b<a.length;b++)if(e[a[b]])e=e[a[b]];else{e={};break}e.items?(this.getAutoSuggestKeywordList().innerHTML=
this.buildKeywordList(e.items),this.show(c,d)):this.hide()}else this.hide()}},addListeners:function(){var a=this;e(this.getAutoSuggestContainer(),"click",function(a){a.stopPropagation()});e(document,"click",function(){a.hideAll()});e(this.getAutoSuggestKeywordList(),"li:click",function(){var b=parseInt(n.get(this,"data-index"));a.selectedItem!=b?a.highlightItem(b):a.selectItem(b)});e(document,"keydown",function(b){if(a.isShown)switch(b.keyCode){case g.UP_ARROW:k.stop(b);a.highlightItem(a.selectedItem-
1);break;case g.DOWN_ARROW:k.stop(b);a.highlightItem(a.selectedItem+1);break;case g.RIGHT_ARROW:k.stop(b);a.hide();break;case g.LEFT_ARROW:k.stop(b);a.hide();break;case g.ENTER:k.stop(b),a.selectItem(a.selectedItem)}});this.hoverClass&&e(this.hoverContainer,"mouseover",function(b){if(a.hoverEnabled){var c=b.target;if(h.contains(c,a.hoverClass))var d=setTimeout(function(){a.showHover(c.innerHTML,b.clientX,b.clientY)},750),g=e(c,s.leave,function(){clearTimeout(d);g.remove()})}})}})});