//>>built
define("net/apachegui/Configuration","dojo/_base/declare dojo/dom dijit/registry dojo/on dojo/request net/apachegui/Editor dojo/_base/json dojo/dom-construct net/apachegui/ConfigurationTree dijit/popup".split(" "),function(l,m,g,h,k,r,s,n,p,q){l("net.apachegui.Configuration",[net.apachegui.Editor],{initialized:!1,loadedTabs:[],file:"",configTree:null,isTreeUpdated:!1,isEditorUpdated:!1,TABS:{EDITOR:"editorTab",TREE:"treeTab"},init:function(){!1===this.initialized&&(this.inherited(arguments),this.addListeners(),
this.loadTab(this.TABS.EDITOR),this.initialized=!0)},loadTab:function(a){-1==this.loadedTabs.indexOf(a)?(a==this.TABS.TREE&&this.buildConfigurationTree(),this.loadedTabs.push(a)):(a==this.TABS.EDITOR&&this.isTreeUpdated&&(this.isTreeUpdated=!1,this.refreshEditor()),a==this.TABS.TREE&&this.isEditorUpdated&&(this.isEditorUpdated=!1,this.configTree.reload()))},refreshEditor:function(){this.setEditorFromFile("../web/Configuration",net.apachegui.Util.getQueryParam("file"))},loadConfigurationTreeJSON:function(a){var b=
net.apachegui.Util.getQueryParam("file");k.get("../web/Configuration",{query:{option:"getConfigurationTree",file:b},handleAs:"json",preventCache:!0,sync:!1}).response.then(function(c){a(c.data.tree)})},buildConfigurationTree:function(){var a=this;this.configTree=new p({id:"configuration_tree",loadTreeJSON:this.loadConfigurationTreeJSON,handleTreeLink:function(c,b){q.close();g.byId("configurationTabs").selectChild(g.byId("editorTab"));a.scrollToLine(b)}});this.configTree.startup();var b=function(c){a.setOpenTime(c.data.lastModifiedTime);
a.isTreeUpdated=!0;a.startUpdateTimer()};this.configTree.on("beforeAddLine",function(c,b){a.stopUpdateTimer()});this.configTree.on("afterAddLine",function(a,d,f){b(f)});this.configTree.on("beforeEditLine",function(b,d){a.stopUpdateTimer()});this.configTree.on("afterEditLine",function(a,d,f){b(f)});this.configTree.on("beforeDeleteLine",function(b,d){a.stopUpdateTimer()});this.configTree.on("afterDeleteLine",function(a,d,f){b(f)});n.place(this.configTree.domNode,m.byId("configuration_tree_container"),
"last")},testConfiguration:function(){var a=net.apachegui.Util.noCloseDialog("Loading","Loading ...");a.show();k.get("../web/Configuration",{query:{option:"test"},handleAs:"json",preventCache:!0,sync:!1}).response.then(function(b){b=b.data;a.remove();net.apachegui.Util.alert("Info",b.result)},function(b){a.remove();net.apachegui.Util.alert("Info",b.response.data.message)})},getActiveFileList:function(){var a=net.apachegui.Util.noCloseDialog("Loading","Loading ...");a.show();net.apachegui.Main.getInstance().getActiveFileList(function(b){for(var c=
"",d=[],f={},e=0;e<b.length;e++)c+='\x3ca target\x3d"_blank" href\x3d"Configuration.jsp?file\x3d'+b[e]+'"\x3e'+b[e]+"\x3c/a\x3e\x3cbr/\x3e",!0===f[b[e]]&&-1==d.indexOf(b[e])&&d.push(b[e]),f[b[e]]=!0;if(0<d.length){c+='\x3cdiv style\x3d"margin-top: 10px;"\x3e\x3cstrong\x3eWarning!\x3c/strong\x3e\x3cbr\x3eThe following file(s) have been included in the configuration multiple times:\x3cul\x3e';for(e=0;e<d.length;e++)c+="\x3cli\x3e"+d[e]+"\x3c/li\x3e";c+="\x3c/ul\x3e\x3c/div\x3e"}net.apachegui.Util.alert("Active File List",
c);a.remove()})},save:function(){var a=net.apachegui.Configuration.getInstance();if(!0!=a.getReadOnly()){var b=net.apachegui.Util.getQueryParam("file"),c=net.apachegui.Util.noCloseDialog("Saving","Saving Please Wait...");c.show();a.stopUpdateTimer();k.post("../web/Configuration",{data:{option:"save",path:b,content:a.editor.getValue()},handleAs:"json",sync:!1}).response.then(function(b){b=b.data;a.clearSaveState();a.setToolbarFades();-1!=b.time&&a.setOpenTime(b.time);c.remove();a.isEditorUpdated=!0;
a.startUpdateTimer()},function(a){c.remove();net.apachegui.Util.alert("Info",a.response.data.message)})}},preview:function(a){net.apachegui.Util.alert("Preview",escape(a))},addListeners:function(){var a=this;this.inherited(arguments);CodeMirror.commands.save=this.save;h(g.byId("editorConfigurationTest"),"click",function(){a.testConfiguration()});h(g.byId("editorConfigurationActiveList"),"click",function(){a.getActiveFileList()});h(g.byId("editorConfigurationSearch"),"click",function(){g.byId("searchConfigurationDialog").show()});
g.byId("configurationTabs").watch("selectedChildWidget",function(b,c,d){a.loadTab(d.id)})}});net.apachegui.Util.setupSingletonInstance(net.apachegui.Configuration)});