//>>built
define("net/apachegui/Init","dojo/_base/declare dojo/dom dijit/registry dojo/on dojo/request dojo/_base/event".split(" "),function(h,c,a,d,g,f){h("net.apachegui.Init",null,{initialized:!1,packageParams:{mac:{serverRoot:"/usr",confFile:"/etc/apache2/httpd.conf",confDirectory:"/etc/apache2",logDirectory:"/var/log/apache2",modulesDirectory:"/usr/libexec/apache2",binFile:"/usr/sbin/apachectl"},debian:{serverRoot:"/etc/apache2",confFile:"/etc/apache2/apache2.conf",confDirectory:"/etc/apache2",logDirectory:"/var/log/apache2",
modulesDirectory:"/usr/lib/apache2/modules",binFile:"/usr/sbin/apache2ctl"},fedora:{serverRoot:"/etc/httpd",confFile:"/etc/httpd/conf/httpd.conf",confDirectory:"/etc/httpd",logDirectory:"/var/log/httpd",modulesDirectory:"/etc/httpd/modules",binFile:"/usr/sbin/apachectl"},suse32:{serverRoot:"/etc/apache2",confFile:"/etc/apache2/httpd.conf",confDirectory:"/etc/apache2",logDirectory:"/var/log/apache2",modulesDirectory:"/usr/lib/apache2",binFile:"/usr/sbin/apache2ctl"},suse64:{serverRoot:"/etc/apache2",
confFile:"/etc/apache2/httpd.conf",confDirectory:"/etc/apache2",logDirectory:"/var/log/apache2",modulesDirectory:"/usr/lib64/apache2",binFile:"/usr/sbin/apache2ctl"}},init:function(){!1===this.initialized&&(this.addListeners(),net.apachegui.Main.getInstance().isWindows()?a.byId("initDialogSource").show():a.byId("initDialogInstallationType").show(),this.initialized=!0)},firstTimeUse:function(){var a=!1;g.get("../web/Init/CheckFirstTime",{handleAs:"json",preventCache:!0,sync:!0}).response.then(function(b){a=
b.data.firstTime},function(a){net.apachegui.Util.alert("Error",a.response.data.message)});return a},hideSourceOption:function(){a.byId("initDialogSource").hide();a.byId("initDialogInstallationType").show()},hidePackageOption:function(){a.byId("initDialogPackage").hide();a.byId("initDialogInstallationType").show()},submit:function(e){var b;"source"==e&&(b={option:"submitSource",serverRoot:c.byId("serverRootSource").value,username:c.byId("usernameSource").value,password1:c.byId("password1Source").value,
password2:c.byId("password2Source").value,enableAuthenticationSource:a.byId("enableAuthenticationSource").get("value")});"package"==e&&(b={option:"submitPackage",serverRoot:c.byId("serverRootPackage").value,confFile:c.byId("confFilePackage").value,confDirectory:c.byId("confDirectoryPackage").value,logDirectory:c.byId("logDirectoryPackage").value,modulesDirectory:c.byId("modulesDirectoryPackage").value,binFile:c.byId("binFilePackage").value,username:c.byId("usernamePackage").value,password1:c.byId("password1Package").value,
password2:c.byId("password2Package").value,enableAuthenticationPackage:a.byId("enableAuthenticationPackage").get("value")});var d=net.apachegui.Util.noCloseDialog("Initializing","Please wait...");d.show();g.post("../web/Init",{data:b,handleAs:"json",sync:!1}).response.then(function(a){document.location="GUISettings.jsp"},function(a){d.remove();net.apachegui.Util.alert("Error",a.response.data.message)})},addListeners:function(){var e=this;d(a.byId("initFormInstallationType"),"submit",function(b){f.stop(b);
this.validate()?!0==c.byId("source").checked?(a.byId("initDialogInstallationType").hide(),b=a.byId("initDialogSource"),b.show()):!0==c.byId("package").checked?(a.byId("initDialogInstallationType").hide(),b=a.byId("initDialogPackage"),b.show()):net.apachegui.Util.alert("Error","You must select an option"):net.apachegui.Util.alert("Error","Please fix fields")});d(a.byId("initFormSource"),"submit",function(a){f.stop(a);this.validate()?e.submit("source"):net.apachegui.Util.alert("Error","Please fix fields")});
d(a.byId("initFormPackage"),"submit",function(a){f.stop(a);this.validate()?e.submit("package"):net.apachegui.Util.alert("Error","Please fix fields")});d(a.byId("hideSourceOption"),"click",function(){e.hideSourceOption()});d(a.byId("hidePackageOption"),"click",function(){e.hidePackageOption()});d(a.byId("operatingSystemSuggestionPackage"),"change",function(b){b=e.packageParams[b]||{};a.byId("serverRootPackage").set("value",b.serverRoot||"");a.byId("confFilePackage").set("value",b.confFile||"");a.byId("confDirectoryPackage").set("value",
b.confDirectory||"");a.byId("logDirectoryPackage").set("value",b.logDirectory||"");a.byId("modulesDirectoryPackage").set("value",b.modulesDirectory||"");a.byId("binFilePackage").set("value",b.binFile||"")})}});net.apachegui.Util.setupSingletonInstance(net.apachegui.Init)});