//>>built
define("net/apachegui/Main",["dojo/_base/declare","dijit/registry","dojo/request","dojo/_base/json","dojo/_base/xhr"],function(h,l,c,m,k){h("net.apachegui.Main",null,{currentOption:"",apacheGuiVersion:"",windows:!1,sessionActive:!0,notRunningDialog:null,apacheVersion:null,confDirectoryPath:"",logDirectoryPath:"",docDirectoryPath:"",getCurrentOption:function(){return this.currentOption},getApacheGuiVersion:function(){return this.apacheGuiVersion},setApacheGuiVersion:function(a){this.apacheGuiVersion=
a},isWindows:function(){return this.windows},setIsWindows:function(a){this.windows=a},isSessionActive:function(){return this.sessionActive},getConfDirectoryPath:function(){if(""!=this.confDirectoryPath)return this.confDirectoryPath;var a=this;c.get("../web/Main",{query:{option:"confFilePath"},handleAs:"json",sync:!0,preventCache:!0}).response.then(function(b){a.confDirectoryPath=b.data.file},function(a){net.apachegui.Util.alert("Error",a.response.data.message)});return this.confDirectoryPath},getLogDirectoryPath:function(){if(""!=
this.logDirectoryPath)return this.logDirectoryPath;var a=this;c.get("../web/Main",{query:{option:"logFilePath"},handleAs:"json",sync:!0,preventCache:!0}).response.then(function(b){a.logDirectoryPath=b.data.file},function(a){net.apachegui.Util.alert("Error",a.response.data.message)});return this.logDirectoryPath},getDocDirectoryPath:function(){if(""!=this.docDirectoryPath)return this.docDirectoryPath;var a=this;c.get("../web/Main",{query:{option:"docFilePath"},handleAs:"json",sync:!0,preventCache:!0}).response.then(function(b){a.docDirectoryPath=
b.data.file},function(a){net.apachegui.Util.alert("Error",a.response.data.message)});return this.docDirectoryPath},validateFileExists:function(a){var b=!1;c.get("../web/Main",{query:{option:"validateFileExists",filename:a},handleAs:"json",sync:!0,preventCache:!0}).response.then(function(a){b=a.data.exists},function(a){net.apachegui.Util.alert("Error",a.response.data.message)});return b},getLastModifiedTime:function(a,b,g){c.get("../web/Main",{query:{option:"lastModifiedTime",path:a},handleAs:"json",
sync:!1,preventCache:!0}).response.then(function(a){b(a)},function(a){g(a)})},getLastModifiedTimes:function(a,b,g){k.post({url:"../web/Main/lastModifiedTimes",postData:JSON.stringify({files:a}),handleAs:"json",headers:{"Content-Type":"application/json"},load:function(a,d){b(a)},error:function(a,b){g(a)}})},getActiveFileList:function(a){c.get("../web/Main",{query:{option:"activeFileList"},handleAs:"json",sync:!1,preventCache:!0}).response.then(function(b){a(b.data.files)},function(a){thisdialog.remove();
net.apachegui.Util.alert("Info",a.response.data.message)})},getApacheVersion:function(a){if(this.apacheVersion)a(this.apacheVersion);else{var b=this;c.get("../web/Main",{query:{option:"apacheVersion"},handleAs:"json",sync:!1,preventCache:!0}).response.then(function(g){b.apacheVersion=g.data.version;a(b.apacheVersion)},function(a){thisdialog.remove();net.apachegui.Util.alert("Info",a.response.data.message)})}},checkSession:function(){var a=this;c.get("../web/Main",{query:{option:"checkSession"},handleAs:"text",
sync:!1,preventCache:!0}).response.then(function(b){if(-1<b.data.indexOf("\x3chtml\x3e")||!a.sessionActive)a.sessionActive=!1,window.location.reload()},function(b){null==a.notRunningDialog&&(a.sessionActive=!1,a.notRunningDialog=net.apachegui.Util.noCloseDialog("Application Unavailable","The ApacheGUI application is not currently running. Your browser window will reload once the application has started."),a.notRunningDialog.show())})},startSessionTimer:function(){net.apachegui.Interval.setInterval(this.checkSession.bind(this),
5E3)},checkServerSyntax:function(){c.get("../web/Main",{query:{option:"checkServerSyntax"},handleAs:"json",preventCache:!0,sync:!1}).response.then(function(a){},function(a){net.apachegui.Util.alert("Info",a.response.data.message)})},init:function(a){this.currentOption=a;if(net.apachegui.Init.getInstance().firstTimeUse())net.apachegui.Init.getInstance().init();else{this.startSessionTimer();this.checkServerSyntax();var b=net.apachegui.Menu.getInstance();b.init();b.setCurrentMenuId(a);b.focusMenuOption(a);
b.isGUISettings(a)&&net.apachegui.GUISettings.getInstance().init();b.isHistory(a)&&net.apachegui.History.getInstance().init();b.isControl(a)&&net.apachegui.Control.getInstance().init();b.isGlobalSettings(a)&&net.apachegui.globalsettings.GlobalSettings.getInstance().init();b.isVirtualHosts(a)&&net.apachegui.VirtualHosts.getInstance().init();b.isGlobalTree(a)&&net.apachegui.GlobalTree.getInstance().init();b.isLogs(a)&&net.apachegui.Logs.getInstance().init();var c=function(a){var b=net.apachegui.Util.getQueryParam("lineNum");
""!=b&&(b=parseInt(b),a.scrollToLine(b))},f;if(b.isDocuments(a)){var d=net.apachegui.Documents.getInstance();f=a.substring(10);this.validateFileExists(f)?d.getIsText()&&(d.init(),d.setEditorFromFile("../web/Documents",f,function(){c(d)})):d.getIsText()&&(d.setValue("File Not Found!!"),d.setReadOnly(),d.clearHistory(),d.clearSaveState(),d.setToolbarFades())}if(b.isConfiguration(a)){var e=net.apachegui.Configuration.getInstance();e.init();f=a.substring(14);this.validateFileExists(f)?e.setEditorFromFile("../web/Configuration",
f,function(){c(e)}):(e.setValue("File Not Found!!"),e.setReadOnly(),e.clearHistory(),e.clearSaveState(),e.setToolbarFades())}}}});net.apachegui.Util.setupSingletonInstance(net.apachegui.Main)});