//>>built
define("net/apachegui/VirtualHosts","dojo/_base/declare dojo/dom dojo/request dijit/registry dojo/on dojo/data/ItemFileWriteStore dojox/grid/DataGrid net/apachegui/TitlePane net/apachegui/RefreshableTree dijit/Tree dijit/tree/ForestStoreModel dojo/store/Observable dijit/Menu dijit/MenuItem dijit/PopupMenuItem dijit/form/Select dojox/fx/scroll dojo/query dojo/_base/array dojo/_base/lang dojo/dom-construct dijit/Tooltip dojo/dom-attr net/apachegui/ConfigurationTree".split(" "),function(t,h,p,f,k,u,
v,w,B,C,D,E,F,G,H,r,I,x,s,J,y,z,K,A){t("net.apachegui.VirtualHosts",null,{virtualHosts:[],currentHierarchicalHostSummaryCount:0,currentTreeSummaryCount:0,currentVirtualHost:null,currentTreeItem:null,treeHostSelect:null,treeGlobalServerName:"",checkModifiedTimes:!0,isModifiedDialogShown:!1,disableEditing:!1,addHostFileSelect:null,initialized:!1,init:function(){!1===this.initialized&&(this.populateTreeVirtualHosts(),this.addListeners(),this.initialized=!0)},areHostsEqual:function(a,d){if(a.ServerName!=
d.ServerName)return!1;var c=a.NetworkInfo,b=d.NetworkInfo;if(c.length!=b.length)return!1;for(var e=!0,q=0;q<c.length&&e;q++)for(var e=!1,g=0;g<b.length;g++)if(c[q].port==b[g].port&&c[q].address==b[g].address){e=!0;break}return e},getLastModifiedFileList:function(){for(var a=[],d=0;d<this.virtualHosts.length;d++)a.push(this.virtualHosts[d].lastModified.file);return a},updateLastModifiedTime:function(a,d,c){var b=this,e=function(d){for(var e=0;e<b.virtualHosts.length;e++)b.virtualHosts[e].lastModified.file==
a&&(b.virtualHosts[e].lastModified.lastModifiedTime=d);b.checkModifiedTimes=!0;c&&c()};d?e(d):net.apachegui.Main.getInstance().getLastModifiedTime(a,function(b){e(b.data.time)},function(b){net.apachegui.Util.alert("Error",b.response.data.message)})},launchLastModifedUpdater:function(){var a=this,d=this.getLastModifiedFileList();0<d.length?net.apachegui.Main.getInstance().getLastModifiedTimes(d,function(c){for(var b=0;b<c.lastModifiedTimes.length;b++)a.updateLastModifiedTime(c.lastModifiedTimes[b].file,
c.lastModifiedTimes[b].lastModifiedTime);a.launchLastModifedUpdaterInterval()},function(a){net.apachegui.Util.alert("Error",JSON.parse(a.response.data).message)}):a.launchLastModifedUpdaterInterval()},launchLastModifedUpdaterInterval:function(){var a=this;net.apachegui.Interval.setInterval(function(){if(a.checkModifiedTimes){var d=a.getLastModifiedFileList();0<d.length&&net.apachegui.Main.getInstance().getLastModifiedTimes(d,function(c){a.isModifiedDialogShown=!1;for(var b=0;b<a.virtualHosts.length;b++)for(var d=
0;d<c.lastModifiedTimes.length;d++)a.virtualHosts[b].lastModified.file==c.lastModifiedTimes[d].file&&a.virtualHosts[b].lastModified.lastModifiedTime!=c.lastModifiedTimes[d].lastModifiedTime&&(a.isModifiedDialogShown||(a.isModifiedDialogShown=!0,a.disableTreeEditing(),net.apachegui.Util.confirmDialog("Reload","It appears that "+a.virtualHosts[b].lastModified.file+" has been updated outside of the editor.\x3cbr/\x3ePlease refresh the page to grab the latest Virtual Host Configuration.\x3cbr/\x3eYou may not edit any virtual hosts until you have refreshed the page.\x3cbr/\x3eWould you like to refresh now?",
function(b){b&&window.location.reload()})),a.virtualHosts[b].lastModified.lastModifiedTime=c.lastModifiedTimes[d].lastModifiedTime)},function(a){net.apachegui.Util.alert("Error",JSON.parse(a.response.data).message)})}},5E3)},valueContainsLogHolder:function(a){return-1<a.indexOf("apacheguilogholder")?!0:!1},showLogHolderError:function(){net.apachegui.Util.alert("Error","The selected line is currently being used by the History functionality.\x3cbr/\x3eTo edit or remove this line you must navigate to the History page and disable the selected Virtual Host.")},
showTreeHostOutOfDateError:function(){net.apachegui.Util.alert("Error","It appears that the VirtualHost has been updated outside of the editor.\x3cbr/\x3ePlease reload the page to grab the latest Virtual Host Configuration.")},showDisabledError:function(){net.apachegui.Util.alert("Error","You may not edit any hosts until you refresh the page.")},showNoConfiguredHosts:function(){h.byId("tree_virtual_host_container").innerHTML="There are no configured Virtual Hosts"},getTreeHostServerName:function(a){return""==
a.ServerName?""==this.treeGlobalServerName?"unknown":this.treeGlobalServerName:a.ServerName},getCurrentTreeContainerId:function(){return"tree-"+this.currentVirtualHost.number},getTreePositionFromHost:function(a){for(var d=0;d<this.virtualHosts.length;d++)if(this.areHostsEqual(this.virtualHosts[d].host,a))return d},getHost:function(a,d){var c={};c.ServerName=a;c.NetworkInfo=d;for(var b=0;b<this.virtualHosts.length;b++){var e=this.virtualHosts[b].host;if(this.areHostsEqual(e,c))return e}return null},
showHostExistsError:function(a){net.apachegui.Util.alert("Error","There is already a Virtual Host with the follwing values:\x3cbr/\x3e\x3cbr/\x3e\x3cstrong\x3eFile\x3c/strong\x3e: "+a.file+" Line: "+a.lineOfStart+"\x3cbr/\x3e\x3cstrong\x3eServerName\x3c/strong\x3e: "+a.ServerName+"\x3cbr/\x3e\x3cstrong\x3eNetworkInfo\x3c/strong\x3e: "+this.buildNetworkInfoString(a)+"\x3cbr/\x3e\x3cbr/\x3eYou may not duplicate Virtual Hosts")},buildNetworkInfoString:function(a){var d="";a=a.NetworkInfo;for(var c=0;c<
a.length;c++)d+=a[c].value;return d},buildTreeHeadingFromHost:function(a){var d=this.getTreeHostServerName(a),c=this.buildNetworkInfoString(a);return'\x3cspan class\x3d"network"\x3e'+d+" "+c+'\x3c/span\x3e\x26nbsp;\x26nbsp;\x26nbsp;\x3cspan class\x3d"file"\x3e\x3ca target\x3d"_blank" href\x3d"Configuration.jsp?file\x3d'+a.file+"\x26lineNum\x3d"+a.lineOfStart+'"\x3e'+a.file+"\x3c/a\x3e Line: "+a.lineOfStart+"\x3c/span\x3e"},buildTreeHostSelectOption:function(a){var d=this.getTreeHostServerName(a);
a=this.buildNetworkInfoString(a);return d+" "+a},buildTreeHostSelect:function(){var a=[];a.push({label:"Select",value:""});for(var d,c=0;c<this.virtualHosts.length;c++)d=this.virtualHosts[c].host,a.push({label:this.buildTreeHostSelectOption(d),value:this.virtualHosts[c].number.toString()});var b;this.treeHostSelect&&(b=this.treeHostSelect.get("value"),this.treeHostSelect.destroyRecursive());this.treeHostSelect=new r({name:"host_select",id:"host_select",options:a});this.treeHostSelect.placeAt(h.byId("select_host_box"));
this.treeHostSelect.startup();b&&this.treeHostSelect.set("value",b,!1);k(this.treeHostSelect,"change",function(){var b=this.get("value");""!=b&&dojox.fx.smoothScroll({node:x("#tree-"+b)[0],win:h.byId("tree_virtual_host_content_pane")}).play()})},buildNetworkInfoArrayFromValue:function(a){var d;p.get("../web/VirtualHosts",{query:{option:"getNetworkInfoArrayFromValue",value:a},handleAs:"json",preventCache:!0,sync:!0}).response.then(function(a){d=a.data.NetworkInfo});return d},disableTreeEditing:function(){this.disableEditing=
!0;f.byId("editLineSubmit").set("disabled",!0);f.byId("addLineSubmit").set("disabled",!0);f.byId("addHostSubmit").set("disabled",!0);for(var a=0;a<this.virtualHosts.length;a++)this.virtualHosts[a].configTree.disableEditing()},reloadAllTreeHosts:function(a){var d,c;if(0==a.length)this.showNoConfiguredHosts();else for(var b=0;b<a.length;b++){d=a[b];for(var e=0;e<this.virtualHosts.length;e++)c=this.virtualHosts[e].host,this.areHostsEqual(c,d)&&(this.virtualHosts[e].host=d)}this.populateHierarchicalVirtualHosts()},
requestAllTreeHosts:function(a,d){p.get("../web/VirtualHosts",{query:{option:"getTreeHosts"},handleAs:"json",preventCache:!0,sync:!1}).response.then(function(c){a(c.data)},function(a){d(a.response.data.message)})},loadVirtualHostTreeJSON:function(a,d){var c=this;if(null!=this.currentVirtualHost){var b=net.apachegui.Util.noCloseDialog("Loading","Loading Tree Host...");b.show();this.requestAllTreeHosts(function(e){e=e.hosts;for(var f,g=0;g<e.length;g++)if(f=e[g],c.areHostsEqual(d.host,f)){a(f.tree);
c.reloadAllTreeHosts(e);break}b.remove()},function(a){b.remove();net.apachegui.Util.alert("Info",a)})}},buildTreeHost:function(a,d,c){var b=this,e="tree-"+this.currentTreeSummaryCount,f={number:this.currentTreeSummaryCount,host:a,lastModified:{file:a.file,lastModifiedTime:0}},g=new A({id:e+"_widget",treeJSON:a.tree,rootType:"VirtualHost",loadTreeJSON:function(a){b.loadVirtualHostTreeJSON(a,f)}});f.tree=g.tree;f.configTree=g;this.virtualHosts.push(f);var l=document.createElement("div");l.id=e;l.innerHTML=
"\x3ch4 id\x3dheading-"+e+"\x3e"+this.buildTreeHeadingFromHost(a)+"\x3c/h4\x3e";l.appendChild(g.domNode);y.place(l,d,c);g.startup();g.on("menufocus",function(){b.currentVirtualHost=f;return!0});g.on("outOfDateError",function(){b.showTreeHostOutOfDateError()});g.on("addDisabledError",function(){b.showDisabledError();return!1});g.on("editDisabledError",function(){b.showDisabledError();return!1});g.on("deleteDisabledError",function(){b.showDisabledError();return!1});g.on("beforeAddLine",function(a,c){if("ServerName"==
a){var d=b.getHost(c,b.currentVirtualHost.host.NetworkInfo);if(d)return b.showHostExistsError(d),!1}b.checkModifiedTimes=!1;return!0});g.on("afterAddLine",function(a,c,d){"ServerName"==a&&(a=b.currentVirtualHost.host,a.ServerName=c,h.byId("heading-"+b.getCurrentTreeContainerId()).innerHTML=b.buildTreeHeadingFromHost(a),b.buildTreeHostSelect());c=d.data;b.updateLastModifiedTime(c.file,c.lastModifiedTime)});g.on("addLineError",function(a,c,d){b.updateLastModifiedTime(b.currentVirtualHost.host.file)});
g.on("beforeEditLine",function(a,c){var d=b.currentVirtualHost.host;if("VirtualHost"==a){var e=b.buildNetworkInfoArrayFromValue(c);if(e=b.getHost(d.ServerName,e))return b.showHostExistsError(e),!1}if("ServerName"==a&&(e=b.getHost(c,d.NetworkInfo)))return b.showHostExistsError(e),!1;b.checkModifiedTimes=!1;return!0});g.on("afterEditLine",function(a,c,d){var e=b.currentVirtualHost.host,f=b.buildNetworkInfoArrayFromValue(c);"VirtualHost"==a&&(e.NetworkInfo=f,h.byId("heading-"+b.getCurrentTreeContainerId()).innerHTML=
b.buildTreeHeadingFromHost(e),b.buildTreeHostSelect());"ServerName"==a&&(e.ServerName=c,h.byId("heading-"+b.getCurrentTreeContainerId()).innerHTML=b.buildTreeHeadingFromHost(e),b.buildTreeHostSelect());a=d.data;b.updateLastModifiedTime(a.file,a.lastModifiedTime)});g.on("editLineError",function(a,c,d){b.updateLastModifiedTime(b.currentVirtualHost.host.file)});g.on("showDeleteDialog",function(a,c){return b.valueContainsLogHolder(c)?(b.showLogHolderError(),!1):!0});g.on("beforeDeleteLine",function(a,
c){var d=b.currentVirtualHost.host;if("ServerName"==a&&(d=b.getHost("",d.NetworkInfo)))return b.showHostExistsError(d),!1;b.checkModifiedTimes=!1;return!0});g.on("afterDeleteLine",function(a,c,d){c=b.currentVirtualHost.host;var e=b.currentVirtualHost.tree;if("VirtualHost"==a){var f=b.getTreePositionFromHost(c);e.destroyRecursive();e=h.byId(b.getCurrentTreeContainerId());e.parentNode.removeChild(e);b.virtualHosts.splice(f,1);b.currentVirtualHost=null;b.buildTreeHostSelect()}"ServerName"==a&&(c.ServerName=
"",h.byId("heading-"+b.getCurrentTreeContainerId()).innerHTML=b.buildTreeHeadingFromHost(c),b.buildTreeHostSelect());a=d.data;b.updateLastModifiedTime(a.file,a.lastModifiedTime);return!0});g.on("deleteLineError",function(a,c,d){b.updateLastModifiedTime(b.currentVirtualHost.host.file)});this.currentTreeSummaryCount++;return l},populateTreeVirtualHosts:function(){var a=this,d=net.apachegui.Util.noCloseDialog("Loading","Loading Tree Hosts...");d.show();this.requestAllTreeHosts(function(c){var b=c.hosts;
a.treeGlobalServerName=c.ServerName;if(0==b.length)a.showNoConfiguredHosts();else{c=!1;for(var e=0;e<b.length&&!c;e++)for(var f=e+1;f<b.length;f++)if(a.areHostsEqual(b[e],b[f])){h.byId("tree_virtual_host_container").innerHTML="There was an error processing the hosts";net.apachegui.Util.alert("Error","There was an error processing the Virtual Hosts.\x3cbr/\x3eThere are duplicate hosts with the following values:\x3cbr/\x3e\x3cbr/\x3e\x3cstrong\x3eFile\x3c/strong\x3e: "+b[e].file+" Line: "+b[e].lineOfStart+
"\x3cbr/\x3e\x3cstrong\x3eServerName\x3c/strong\x3e: "+b[e].ServerName+"\x3cbr/\x3e\x3cstrong\x3eNetworkInfo\x3c/strong\x3e: "+a.buildNetworkInfoString(b[e])+"\x3cbr/\x3e\x3cbr/\x3e\x3cstrong\x3eFile\x3c/strong\x3e: "+b[f].file+" Line: "+b[f].lineOfStart+"\x3cbr/\x3e\x3cstrong\x3eServerName\x3c/strong\x3e: "+b[f].ServerName+"\x3cbr/\x3e\x3cstrong\x3eNetworkInfo\x3c/strong\x3e: "+a.buildNetworkInfoString(b[f])+"\x3cbr/\x3e\x3cbr/\x3eYou must fix the configuration error before using the Virtual Host functionality");
c=!0;break}if(!c)for(e=0;e<b.length;e++)a.buildTreeHost(b[e],h.byId("tree_virtual_host_container"),"last")}a.buildTreeHostSelect();a.populateHierarchicalVirtualHosts();a.launchLastModifedUpdater();d.remove()},function(a){d.remove();net.apachegui.Util.alert("Info",a)})},populateHierarchicalVirtualHosts:function(){var a=this,d=function(c,b,d,f,g){f=""==b.ServerName?""==f?"unknown":f:b.ServerName;c=new u({data:{identifier:"id",label:"name",items:[{id:"networkname",name:"Network",value:c},{id:"port",
name:"Port",value:-1==b.NetworkInfo.port?"":b.NetworkInfo.port},{id:"address",name:"Address",value:b.NetworkInfo.address},{id:"file",name:"File",value:'\x3ca target\x3d"_blank" href\x3d"Configuration.jsp?file\x3d'+b.file+"\x26lineNum\x3d"+b.lineOfStart+'"\x3e'+b.file+"\x3c/a\x3e Line: "+b.lineOfStart},{id:"documentroot",name:"DocumentRoot",value:""==b.DocumentRoot?""==g?"unknown":g:b.DocumentRoot},{id:"servername",name:"ServerName",value:f},{id:"serveralias",name:"ServerAlias",value:b.ServerAlias}]}});
c=new v({id:"grid-"+a.currentHierarchicalHostSummaryCount,store:c,structure:[[{name:" ",field:"name",width:"150px"},{name:" ",field:"value",width:"auto"}]],selectable:!0,style:"width:100%;",autoHeight:!0,escapeHTMLInData:!1,rowSelector:"20px"});f=new w({title:f,content:c,open:!1});h.byId(d).appendChild(f.domNode);f.startup();c.startup();a.currentHierarchicalHostSummaryCount++};p.get("../web/VirtualHosts",{query:{option:"getHierarchicalHosts"},handleAs:"json",preventCache:!0,sync:!1}).response.then(function(c){var b=
c.data;c=h.byId("name_virtual_host_container");var e=h.byId("other_virtual_host_container");s.forEach(f.findWidgets(c),function(a){a.destroyRecursive()});c.innerHTML="";s.forEach(f.findWidgets(e),function(a){a.destroyRecursive()});e.innerHTML="";var k=b.hosts,g=b.ServerName,b=b.DocumentRoot;for(host in k){var l=k[host];if(1<l.length)for(var m=0;m<l.length;m++)if(0==m){var n=document.createElement("div");n.innerHTML="\x3ch4\x3e"+host+"\x3c/h4\x3e";c.appendChild(n);n=document.createElement("div");n.innerHTML=
'\x3ch5\x3eDefault \x3cspan id\x3d"default_dialog_'+a.currentHierarchicalHostSummaryCount+'"  class\x3d"warningTooltip"\x3e\x3c/span\x3e\x3c/h5\x3e';c.appendChild(n);new z({connectId:["default_dialog_"+a.currentHierarchicalHostSummaryCount],label:"The default Virtual Host is used when a request comes in with a domain that does not match a ServerName or ServerAlias for the specified address and port."});d(host,l[m],"name_virtual_host_container",g,b);n=document.createElement("div");n.innerHTML="\x3ch5\x3eOther Virtual Hosts\x3c/h5\x3e";
c.appendChild(n)}else d(host,l[m],"name_virtual_host_container",g,b);else n=document.createElement("div"),n.innerHTML="\x3ch4\x3e"+host+"\x3c/h4\x3e",e.appendChild(n),d(host,l[0],"other_virtual_host_container",g,b)}""==c.innerHTML.trim()&&(c.innerHTML="\x3cp\x3eThere are no configured Name Virtual Hosts\x3c/p\x3e");""==e.innerHTML.trim()&&(e.innerHTML="\x3cp\x3eThere are no other configured Virtual Hosts\x3c/p\x3e")},function(a){thisdialog.remove();net.apachegui.Util.alert("Info",a.response.data.message)})},
buildAddHostFileSelect:function(a){var d=[];d.push({label:"Select",value:""});for(var c=0;c<a.length;c++)d.push({label:a[c],value:a[c]});this.addHostFileSelect&&this.addHostFileSelect.destroyRecursive();this.addHostFileSelect=new r({name:"addHostFile",id:"addHostFile",options:d});this.addHostFileSelect.placeAt(h.byId("add_host_select_box"));this.addHostFileSelect.startup();k(this.addHostFileSelect,"change",function(){""!=this.get("value")?(f.byId("addHostNewFile").set("value",""),f.byId("addHostNewFile").set("disabled",
!0)):f.byId("addHostNewFile").set("disabled",!1)})},submitAddHost:function(){var a=this,d=h.byId("addHostAllAddress").checked,c=f.byId("addHostAddress").get("value").trim(),b=f.byId("addHostPort").get("value").trim(),e=f.byId("addHostServerName").get("value").trim(),k=f.byId("addHostDocumentRoot").get("value").trim(),g=this.addHostFileSelect.get("value"),l=f.byId("addHostNewFile").get("value").trim();if(!1==d&&""==c)net.apachegui.Util.alert("Error","You must specify either All IP's and hosts or a specific IP or host.");
else if(""!=b&&isNaN(b))net.apachegui.Util.alert("Error","The Port must be numeric");else if(""==l&&""==g)net.apachegui.Util.alert("Error","You must specify a file");else if(c=!0==d?"*":c,g=""==g?l:g,d=this.getHost(e,[{port:""==b?-1:parseInt(b),address:c,value:""}]))this.showHostExistsError(d);else{var m=net.apachegui.Util.noCloseDialog("Adding","Adding Please Wait...");m.show();this.checkModifiedTimes=!1;p.post("../web/VirtualHosts",{data:{option:"addHost",hostAddress:c,port:b,serverName:e,documentRoot:k,
file:g},handleAs:"json",sync:!1}).response.then(function(b){var c=b.data.hosts;1==c.length&&(h.byId("tree_virtual_host_container").innerHTML="");for(var d=!1,e=b=0;e<a.virtualHosts.length;e++)if(!a.areHostsEqual(a.virtualHosts[e].host,c[e])){a.buildTreeHost(c[e],h.byId("tree-"+a.virtualHosts[e].number),"before");d=!0;b=e;break}if(d){c=a.virtualHosts[a.virtualHosts.length-1];for(e=a.virtualHosts.length-1;e>b;e--)a.virtualHosts[e]=a.virtualHosts[e-1];a.virtualHosts[b]=c}else b=c.length-1,a.buildTreeHost(c[c.length-
1],h.byId("tree_virtual_host_container"),"last");a.buildTreeHostSelect();m.remove();f.byId("addHostDialog").hide();a.treeHostSelect.set("value",a.virtualHosts[b].number);g=a.virtualHosts[b].lastModified.file;""!=l?(net.apachegui.Menu.getInstance().refresh(),a.updateLastModifiedTime(g,null,function(){a.checkModifiedTimes=!1;a.updateLastModifiedTime(net.apachegui.Settings.getInstance().getSetting(net.apachegui.Settings.getInstance().settingsMap.confFile))})):a.updateLastModifiedTime(g);m=null;m=net.apachegui.Util.noCloseDialog("Loading",
"Loading Tree Hosts...");m.show();a.requestAllTreeHosts(function(b){a.reloadAllTreeHosts(b.hosts);m.remove()},function(a){m.remove();net.apachegui.Util.alert("Info",a)})},function(a){m.remove();net.apachegui.Util.alert("Error",a.response.data.message)})}},addListeners:function(){var a=this;k(f.byId("addHostButton"),"click",function(){if(a.disableEditing)a.showDisabledError();else{var d=net.apachegui.Util.noCloseDialog("Loading","Loading Active Files ...");d.show();net.apachegui.Main.getInstance().getActiveFileList(function(c){h.byId("addHostAllAddress").checked=
!1;f.byId("addHostAddress").set("value","");f.byId("addHostAddress").set("disabled",!1);f.byId("addHostPort").set("value","");f.byId("addHostServerName").set("value","");f.byId("addHostDocumentRoot").set("value","");f.byId("addHostNewFile").set("value","");f.byId("addHostNewFile").set("disabled",!1);a.buildAddHostFileSelect(c);f.byId("addHostDialog").show();d.remove()})}});k(h.byId("addHostAllAddress"),"click",function(){!0==this.checked?(f.byId("addHostAddress").set("value",""),f.byId("addHostAddress").set("disabled",
!0)):f.byId("addHostAddress").set("disabled",!1)});k(f.byId("addHostAddress"),"focus",function(){h.byId("addHostAllAddress").disabled=!0});k(f.byId("addHostAddress"),"blur",function(){""==f.byId("addHostAddress").get("value").trim()&&(h.byId("addHostAllAddress").disabled=!1)});k(f.byId("addHostNewFile"),"focus",function(){f.byId("addHostFile").set("disabled",!0)});k(f.byId("addHostNewFile"),"blur",function(){""==f.byId("addHostNewFile").get("value").trim()&&f.byId("addHostFile").set("disabled",!1)});
k(f.byId("addHostCancel"),"click",function(){f.byId("addHostDialog").hide()});k(f.byId("addHostSubmit"),"click",function(){a.submitAddHost()})}});net.apachegui.Util.setupSingletonInstance(net.apachegui.VirtualHosts)});