/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/7.0.53
 * Generated at: 2015-12-29 03:56:07 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.WEB_002dINF.jsp.views.editor;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class EditorMenu_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fc_005fif_0026_005ftest;

  private javax.el.ExpressionFactory _el_expressionfactory;
  private org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public void _jspInit() {
    _005fjspx_005ftagPool_005fc_005fif_0026_005ftest = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
    _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
    _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
  }

  public void _jspDestroy() {
    _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.release();
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("<div id=\"editorPane\" class=\"centerPanel\" data-dojo-type=\"dijit.layout.ContentPane\" data-dojo-props=\"region: 'top', title:'Modify'\">\n");
      out.write("\n");
      out.write("<div id=\"editorMenu\" data-dojo-type=\"dijit.MenuBar\">\n");
      out.write("    <div id=\"editorFile\" data-dojo-type=\"dijit.PopupMenuBarItem\">\n");
      out.write("        <span>File</span>\n");
      out.write("        <div id=\"editorFileMenu\" data-dojo-type=\"dijit.Menu\">\n");
      out.write("            <div id=\"editorFileSave\" data-dojo-type=\"dijit.MenuItem\" data-dojo-props=\"disabled: 'true'\">\n");
      out.write("                <div class=\"editorMenuItem\">\n");
      out.write("                    <div class=\"option\">Save</div>\n");
      out.write("                    <div id=\"save\" class=\"command\">Ctrl+S</div>\n");
      out.write("                </div>\n");
      out.write("            </div>\n");
      out.write("            <div id=\"editorFileNew\" data-dojo-type=\"dijit.MenuItem\">\n");
      out.write("                <div class=\"editorMenuItem\">\n");
      out.write("                    <div class=\"option\">New</div>\n");
      out.write("                </div>\n");
      out.write("            </div>\n");
      out.write("        </div>\n");
      out.write("    </div>\n");
      out.write("    <div id=\"editorEdit\" data-dojo-type=\"dijit.PopupMenuBarItem\">\n");
      out.write("        <span>Edit</span>\n");
      out.write("        <div id=\"editorEditMenu\" data-dojo-type=\"dijit.Menu\">\n");
      out.write("            <div id=\"editorEditUndo\" data-dojo-type=\"dijit.MenuItem\">\n");
      out.write("                <div class=\"editorMenuItem\">\n");
      out.write("                    <div class=\"option\">Undo</div>\n");
      out.write("                    <div id=\"undo\" class=\"command\">Ctrl+Z</div>\n");
      out.write("                </div>\n");
      out.write("            </div>\n");
      out.write("            <div id=\"editorEditRedo\" data-dojo-type=\"dijit.MenuItem\">\n");
      out.write("                <div class=\"editorMenuItem\">\n");
      out.write("                    <div class=\"option\">Redo</div>\n");
      out.write("                    <div id=\"redo\" class=\"command\">Ctrl+Shift+Z</div>\n");
      out.write("                </div>\n");
      out.write("            </div>\n");
      out.write("            <div id=\"editorEditFind\" data-dojo-type=\"dijit.MenuItem\">\n");
      out.write("                <div class=\"editorMenuItem\">\n");
      out.write("                    <div class=\"option\">Find</div>\n");
      out.write("                    <div id=\"find\" class=\"command\">Ctrl+F</div>\n");
      out.write("                </div>\n");
      out.write("            </div>\n");
      out.write("            <div id=\"editorEditReplace\" data-dojo-type=\"dijit.MenuItem\">\n");
      out.write("                <div class=\"editorMenuItem\">\n");
      out.write("                    <div class=\"option\">Replace</div>\n");
      out.write("                    <div id=\"replace\" class=\"command\">Shift-Ctrl-F</div>\n");
      out.write("                </div>\n");
      out.write("            </div>\n");
      out.write("            <div id=\"editorEditReplaceAll\" data-dojo-type=\"dijit.MenuItem\">\n");
      out.write("                <div class=\"editorMenuItem\">\n");
      out.write("                    <div class=\"option\">Replace All</div>\n");
      out.write("                    <div id=\"replaceAll\" class=\"command\">Shift-Ctrl-R</div>\n");
      out.write("                </div>\n");
      out.write("            </div>\n");
      out.write("            <div id=\"editorEditAutoFormat\" data-dojo-type=\"dijit.MenuItem\">\n");
      out.write("                <div class=\"editorMenuItem\">\n");
      out.write("                    <div class=\"option\">Auto Format</div>\n");
      out.write("                    <div id=\"autoFormat\" class=\"command\">Shift-Ctrl-F</div>\n");
      out.write("                </div>\n");
      out.write("            </div>\n");
      out.write("            <div id=\"editorEditComment\" data-dojo-type=\"dijit.MenuItem\">\n");
      out.write("                <div class=\"editorMenuItem\">\n");
      out.write("                    <div class=\"option\">Comment</div>\n");
      out.write("                    <div id=\"comment\" class=\"command\">Shift-Ctrl-C</div>\n");
      out.write("                </div>\n");
      out.write("            </div>\n");
      out.write("            <div id=\"editorEditUnComment\" data-dojo-type=\"dijit.MenuItem\">\n");
      out.write("                <div class=\"editorMenuItem\">\n");
      out.write("                    <div class=\"option\">Uncomment</div>\n");
      out.write("                    <div id=\"unComment\" class=\"command\">Shift-Ctrl-U</div>\n");
      out.write("                </div>\n");
      out.write("            </div>\n");
      out.write("            <div id=\"editorEditTheme\" data-dojo-type=\"dijit.PopupMenuItem\">\n");
      out.write("                <span>Theme</span>\n");
      out.write("                <div id=\"editorEditThemeMenu\" data-dojo-type=\"dijit.Menu\">\n");
      out.write("                    <div id=\"default\" data-dojo-type=\"dijit.MenuItem\" data-dojo-props=\"class: 'editor_theme'\">\n");
      out.write("                        default\n");
      out.write("                    </div>\n");
      out.write("                    <div id=\"ambiance\" data-dojo-type=\"dijit.MenuItem\" data-dojo-props=\"class: 'editor_theme'\">\n");
      out.write("                        ambiance\n");
      out.write("                    </div>\n");
      out.write("                    <div id=\"blackboard\" data-dojo-type=\"dijit.MenuItem\" data-dojo-props=\"class: 'editor_theme'\">\n");
      out.write("                        blackboard\n");
      out.write("                    </div>\n");
      out.write("                    <div id=\"cobalt\" data-dojo-type=\"dijit.MenuItem\" data-dojo-props=\"class: 'editor_theme'\">\n");
      out.write("                        cobalt\n");
      out.write("                    </div>\n");
      out.write("                    <div id=\"eclipse\" data-dojo-type=\"dijit.MenuItem\" data-dojo-props=\"class: 'editor_theme'\">\n");
      out.write("                        eclipse\n");
      out.write("                    </div>\n");
      out.write("                    <div id=\"elegant\" data-dojo-type=\"dijit.MenuItem\" data-dojo-props=\"class: 'editor_theme'\">\n");
      out.write("                        elegant\n");
      out.write("                    </div>\n");
      out.write("                    <div id=\"erlang-dark\" data-dojo-type=\"dijit.MenuItem\" data-dojo-props=\"class: 'editor_theme'\">\n");
      out.write("                        erlang-dark\n");
      out.write("                    </div>\n");
      out.write("                    <div id=\"lesser-dark\" data-dojo-type=\"dijit.MenuItem\" data-dojo-props=\"class: 'editor_theme'\">\n");
      out.write("                        lesser-dark\n");
      out.write("                    </div>\n");
      out.write("                    <div id=\"monokai\" data-dojo-type=\"dijit.MenuItem\" data-dojo-props=\"class: 'editor_theme'\">\n");
      out.write("                        monokai\n");
      out.write("                    </div>\n");
      out.write("                    <div id=\"neat\" data-dojo-type=\"dijit.MenuItem\" data-dojo-props=\"class: 'editor_theme'\">\n");
      out.write("                        neat\n");
      out.write("                    </div>\n");
      out.write("                    <div id=\"night\" data-dojo-type=\"dijit.MenuItem\" data-dojo-props=\"class: 'editor_theme'\">\n");
      out.write("                        night\n");
      out.write("                    </div>\n");
      out.write("                    <div id=\"vibrant-ink\" data-dojo-type=\"dijit.MenuItem\" data-dojo-props=\"class: 'editor_theme'\">\n");
      out.write("                        vibrant-ink\n");
      out.write("                    </div>\n");
      out.write("                    <div id=\"xq-dark\" data-dojo-type=\"dijit.MenuItem\" data-dojo-props=\"class: 'editor_theme'\">\n");
      out.write("                        xq-dark\n");
      out.write("                    </div>\n");
      out.write("                </div>\n");
      out.write("            </div><!-- end of sub-menu -->\n");
      out.write("            <div id=\"editorEditTabs\" data-dojo-type=\"dijit.PopupMenuItem\">\n");
      out.write("                <span>Tabs</span>\n");
      out.write("                <div id=\"editorEditTabsMenu\" data-dojo-type=\"dijit.Menu\">\n");
      out.write("                    <div id=\"editorEditHideTabs\" data-dojo-type=\"dijit.MenuItem\">\n");
      out.write("                        Hide Tabs\n");
      out.write("                    </div>\n");
      out.write("                    <div id=\"editorEditShowTabs\" data-dojo-type=\"dijit.MenuItem\">\n");
      out.write("                        Show Tabs\n");
      out.write("                    </div>\n");
      out.write("                </div>\n");
      out.write("            </div> \n");
      out.write("            <div id=\"editorEditMode\" data-dojo-type=\"dijit.PopupMenuItem\">\n");
      out.write("                <span>Mode</span>\n");
      out.write("                <div id=\"editorEditModeMenu\" data-dojo-type=\"dijit.Menu\">\n");
      out.write("                    <div id=\"plain\" data-dojo-type=\"dijit.MenuItem\" data-dojo-props=\"class: 'editor_mode'\">\n");
      out.write("                        Plain Text\n");
      out.write("                    </div>\n");
      out.write("                    <div id=\"conf\" data-dojo-type=\"dijit.MenuItem\" data-dojo-props=\"class: 'editor_mode'\">\n");
      out.write("                        Conf\n");
      out.write("                    </div>\n");
      out.write("                    <div id=\"html\" data-dojo-type=\"dijit.MenuItem\" data-dojo-props=\"class: 'editor_mode'\">\n");
      out.write("                        HTML\n");
      out.write("                    </div>\n");
      out.write("                    <div id=\"css\" data-dojo-type=\"dijit.MenuItem\" data-dojo-props=\"class: 'editor_mode'\">\n");
      out.write("                        CSS\n");
      out.write("                    </div>\n");
      out.write("                    <div id=\"xml\" data-dojo-type=\"dijit.MenuItem\" data-dojo-props=\"class: 'editor_mode'\">\n");
      out.write("                        XML\n");
      out.write("                    </div>\n");
      out.write("                    <div id=\"javascript\" data-dojo-type=\"dijit.MenuItem\" data-dojo-props=\"class: 'editor_mode'\">\n");
      out.write("                        JavaScript\n");
      out.write("                    </div>\n");
      out.write("                    <div id=\"json\" data-dojo-type=\"dijit.MenuItem\" data-dojo-props=\"class: 'editor_mode'\">\n");
      out.write("                        JSON\n");
      out.write("                    </div>\n");
      out.write("                    <div id=\"php\" data-dojo-type=\"dijit.MenuItem\" data-dojo-props=\"class: 'editor_mode'\">\n");
      out.write("                        PHP\n");
      out.write("                    </div>\n");
      out.write("                    <div id=\"python\" data-dojo-type=\"dijit.MenuItem\" data-dojo-props=\"class: 'editor_mode'\">\n");
      out.write("                        Python\n");
      out.write("                    </div>\n");
      out.write("                    <div id=\"perl\" data-dojo-type=\"dijit.MenuItem\" data-dojo-props=\"class: 'editor_mode'\">\n");
      out.write("                        Perl\n");
      out.write("                    </div>\n");
      out.write("                    <div id=\"shell\" data-dojo-type=\"dijit.MenuItem\" data-dojo-props=\"class: 'editor_mode'\">\n");
      out.write("                        Shell\n");
      out.write("                    </div>\n");
      out.write("                    <div id=\"properties\" data-dojo-type=\"dijit.MenuItem\" data-dojo-props=\"class: 'editor_mode'\">\n");
      out.write("                        Properties\n");
      out.write("                    </div>\n");
      out.write("                </div>\n");
      out.write("            </div>\n");
      out.write("        </div>\n");
      out.write("    </div>\n");
      out.write("\n");
      out.write("    ");
      out.write("\n");
      out.write("\n");
      out.write("    ");
      out.write("\n");
      out.write("    ");
      if (_jspx_meth_c_005fif_005f0(_jspx_page_context))
        return;
      out.write("\n");
      out.write("\n");
      out.write("    ");
      if (_jspx_meth_c_005fif_005f1(_jspx_page_context))
        return;
      out.write("\n");
      out.write("</div>\n");
      out.write("<div id=\"menu_toolbar\" dojoType=\"dijit.Toolbar\">\n");
      out.write("    <div dojoType=\"dijit.form.Button\" id=\"editorToolbarSave\" iconClass=\"dijitEditorIcon dijitEditorIconSave\" showLabel=\"false\">\n");
      out.write("        Save\n");
      out.write("    </div>\n");
      out.write("    <div dojoType=\"dijit.form.Button\" id=\"editorToolbarRedo\" iconClass=\"dijitEditorIcon dijitEditorIconRedo\" showLabel=\"false\">\n");
      out.write("        Redo\n");
      out.write("    </div>\n");
      out.write("    <div dojoType=\"dijit.form.Button\" id=\"editorToolbarUndo\" iconClass=\"dijitEditorIcon dijitEditorIconUndo\" showLabel=\"false\">\n");
      out.write("        Undo\n");
      out.write("    </div>\n");
      out.write("    <div dojoType=\"dijit.form.Button\" id=\"editorToolbarTabs\" iconClass=\"dijitEditorIcon dijitEditorIconIndent\" showLabel=\"false\">\n");
      out.write("        Toggle Tab Visibility\n");
      out.write("    </div>\n");
      out.write("    \n");
      out.write("    <select name=\"editorThemeSelector\" id=\"editorThemeSelector\" dojoType=\"dijit.form.Select\">\n");
      out.write("        <option value=\"default\">\n");
      out.write("            default\n");
      out.write("        </option>\n");
      out.write("        <option value=\"ambiance\">\n");
      out.write("            ambiance\n");
      out.write("        </option>\n");
      out.write("        <option value=\"blackboard\">\n");
      out.write("            blackboard\n");
      out.write("        </option>\n");
      out.write("        <option value=\"cobalt\">\n");
      out.write("            cobalt\n");
      out.write("        </option>\n");
      out.write("        <option value=\"eclipse\">\n");
      out.write("            eclipse\n");
      out.write("        </option>\n");
      out.write("        <option value=\"elegant\">\n");
      out.write("            elegant\n");
      out.write("        </option>\n");
      out.write("        <option value=\"erlang-dark\">\n");
      out.write("            erlang-dark\n");
      out.write("        </option>\n");
      out.write("        <option value=\"lesser-dark\">\n");
      out.write("            lesser-dark\n");
      out.write("        </option>\n");
      out.write("        <option value=\"monokai\">\n");
      out.write("            monokai\n");
      out.write("        </option>\n");
      out.write("        <option value=\"neat\">\n");
      out.write("            neat\n");
      out.write("        </option>\n");
      out.write("        <option value=\"night\">\n");
      out.write("            night\n");
      out.write("        </option>\n");
      out.write("        <option value=\"vibrant-ink\">\n");
      out.write("            vibrant-ink\n");
      out.write("        </option>\n");
      out.write("        <option value=\"xq-dark\">\n");
      out.write("            xq-dark\n");
      out.write("        </option>\n");
      out.write("    </select>\n");
      out.write("\n");
      out.write("    <select name=\"editorModeSelector\" id=\"editorModeSelector\" dojoType=\"dijit.form.Select\">\n");
      out.write("        <option value=\"plain\">\n");
      out.write("            Plain Text\n");
      out.write("        </option>\n");
      out.write("        <option value=\"conf\">\n");
      out.write("            Conf\n");
      out.write("        </option>\n");
      out.write("        <option value=\"html\">\n");
      out.write("            HTML\n");
      out.write("        </option>\n");
      out.write("        <option value=\"css\">\n");
      out.write("            CSS\n");
      out.write("        </option>\n");
      out.write("        <option value=\"xml\">\n");
      out.write("            XML\n");
      out.write("        </option>\n");
      out.write("        <option value=\"javascript\">\n");
      out.write("            JavaScript\n");
      out.write("        </option>\n");
      out.write("        <option value=\"json\">\n");
      out.write("            JSON\n");
      out.write("        </option>\n");
      out.write("        <option value=\"php\">\n");
      out.write("            PHP\n");
      out.write("        </option>\n");
      out.write("        <option value=\"python\">\n");
      out.write("            Python\n");
      out.write("        </option>\n");
      out.write("        <option value=\"perl\">\n");
      out.write("            Perl\n");
      out.write("        </option>\n");
      out.write("        <option value=\"shell\">\n");
      out.write("            Shell\n");
      out.write("        </option>\n");
      out.write("        <option value=\"properties\">\n");
      out.write("            Properties\n");
      out.write("        </option>\n");
      out.write("    </select>\n");
      out.write("\n");
      out.write("    <span id=\"filename_container\"></span>\n");
      out.write("\n");
      out.write("</div>\n");
      out.write("\n");
      out.write("\n");
      out.write("</div>\n");
      out.write("<!-- end of sub-menu -->\n");
      out.write("\n");
      out.write("<div dojoType=\"dijit.Dialog\" id=\"editorNewFileDialog\" title=\"New File\" style=\"display: none\">\n");
      out.write("    <form dojoType=\"dijit.form.Form\" id=\"editorNewFileForm\">\n");
      out.write("        <table>\n");
      out.write("            <tr class=\"dijitDialogPaneContentArea\">\n");
      out.write("                <td>\n");
      out.write("                    <label for='editorNewFileFilename'>\n");
      out.write("                        Filename:\n");
      out.write("                        </label>\n");
      out.write("                   </td>\n");
      out.write("                <td>\n");
      out.write("                    <div dojoType=\"dijit.form.ValidationTextBox\" required=\"true\" id=\"editorNewFileFilename\">\n");
      out.write("                    </div>\n");
      out.write("                </td>\n");
      out.write("            </tr>\n");
      out.write("        </table>\n");
      out.write("        <div class=\"dijitDialogPaneActionBar\">\n");
      out.write("            <button id=\"editorNewFileCancel\" dojoType=\"dijit.form.Button\" type=\"button\">\n");
      out.write("                Cancel\n");
      out.write("            </button>\n");
      out.write("            <button dojoType=\"dijit.form.Button\" type=\"submit\">\n");
      out.write("                Submit\n");
      out.write("            </button>\n");
      out.write("        </div>\n");
      out.write("    </form>\n");
      out.write("</div>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try { out.clearBuffer(); } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }

  private boolean _jspx_meth_c_005fif_005f0(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    javax.servlet.http.HttpServletRequest request = (javax.servlet.http.HttpServletRequest)_jspx_page_context.getRequest();
    javax.servlet.http.HttpServletResponse response = (javax.servlet.http.HttpServletResponse)_jspx_page_context.getResponse();
    //  c:if
    org.apache.taglibs.standard.tag.rt.core.IfTag _jspx_th_c_005fif_005f0 = (org.apache.taglibs.standard.tag.rt.core.IfTag) _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.get(org.apache.taglibs.standard.tag.rt.core.IfTag.class);
    _jspx_th_c_005fif_005f0.setPageContext(_jspx_page_context);
    _jspx_th_c_005fif_005f0.setParent(null);
    // /WEB-INF/jsp/views/editor/EditorMenu.jsp(177,4) name = test type = boolean reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
    _jspx_th_c_005fif_005f0.setTest(((java.lang.Boolean) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${option == 'Configuration'}", java.lang.Boolean.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false)).booleanValue());
    int _jspx_eval_c_005fif_005f0 = _jspx_th_c_005fif_005f0.doStartTag();
    if (_jspx_eval_c_005fif_005f0 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
      do {
        out.write("\n");
        out.write("        ");
        org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, "/jsp/editor/ConfigurationExtension.jsp", out, true);
        out.write("\n");
        out.write("    ");
        int evalDoAfterBody = _jspx_th_c_005fif_005f0.doAfterBody();
        if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
          break;
      } while (true);
    }
    if (_jspx_th_c_005fif_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
      _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.reuse(_jspx_th_c_005fif_005f0);
      return true;
    }
    _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.reuse(_jspx_th_c_005fif_005f0);
    return false;
  }

  private boolean _jspx_meth_c_005fif_005f1(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    javax.servlet.http.HttpServletRequest request = (javax.servlet.http.HttpServletRequest)_jspx_page_context.getRequest();
    javax.servlet.http.HttpServletResponse response = (javax.servlet.http.HttpServletResponse)_jspx_page_context.getResponse();
    //  c:if
    org.apache.taglibs.standard.tag.rt.core.IfTag _jspx_th_c_005fif_005f1 = (org.apache.taglibs.standard.tag.rt.core.IfTag) _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.get(org.apache.taglibs.standard.tag.rt.core.IfTag.class);
    _jspx_th_c_005fif_005f1.setPageContext(_jspx_page_context);
    _jspx_th_c_005fif_005f1.setParent(null);
    // /WEB-INF/jsp/views/editor/EditorMenu.jsp(181,4) name = test type = boolean reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
    _jspx_th_c_005fif_005f1.setTest(((java.lang.Boolean) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${option == 'Documents'}", java.lang.Boolean.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false)).booleanValue());
    int _jspx_eval_c_005fif_005f1 = _jspx_th_c_005fif_005f1.doStartTag();
    if (_jspx_eval_c_005fif_005f1 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
      do {
        out.write("\n");
        out.write("        ");
        org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, "/jsp/editor/DocumentsExtension.jsp", out, true);
        out.write("\n");
        out.write("    ");
        int evalDoAfterBody = _jspx_th_c_005fif_005f1.doAfterBody();
        if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
          break;
      } while (true);
    }
    if (_jspx_th_c_005fif_005f1.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
      _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.reuse(_jspx_th_c_005fif_005f1);
      return true;
    }
    _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.reuse(_jspx_th_c_005fif_005f1);
    return false;
  }
}
