/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/7.0.53
 * Generated at: 2015-12-29 03:56:07 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.WEB_002dINF.jsp.views;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class Configuration_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private javax.el.ExpressionFactory _el_expressionfactory;
  private org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public void _jspInit() {
    _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
    _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("    \n");
      out.write("<!DOCTYPE html>\n");
      out.write("<html>\n");
      out.write("<head>\n");
      out.write("\n");
      out.write("    ");
      out.write("\n");
      out.write("    ");
      org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, "/jsp/Head.jsp", out, true);
      out.write("\n");
      out.write("\n");
      out.write("    ");
      org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, "/jsp/editor/EditorIncludes.jsp", out, true);
      out.write("\n");
      out.write("\n");
      out.write("    <script>\n");
      out.write("        require([\n");
      out.write("             ");
      org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, "/jsp/RequireIncludes.jsp", out, true);
      out.write("\n");
      out.write("         ], function() {\n");
      out.write("             require([\n");
      out.write("                      \"net/apachegui/Configuration\",\n");
      out.write("                      \"dijit/MenuBar\",\n");
      out.write("                      \"dijit/PopupMenuBarItem\",\n");
      out.write("                      \"dijit/Toolbar\",\n");
      out.write("                      \"dijit/form/Select\",\n");
      out.write("                       \"dojo/dom\",\n");
      out.write("                      \"dojo/parser\",\n");
      out.write("                      \"dojo/domReady!\"\n");
      out.write("             ], function(Configuration, MenuBar, PopupMenuBarItem, Toolbar, Select, dom, parser) {\n");
      out.write("                 parser.parse();\n");
      out.write("\n");
      out.write("                 var configuration = net.apachegui.Configuration.getInstance();\n");
      out.write("\n");
      out.write("                 configuration.setEditor('fileTextArea', ");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${mode}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
      out.write(");\n");
      out.write("                 configuration.setOpenTime(");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${openTime}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
      out.write(");\n");
      out.write("\n");
      out.write("                 var editorDiv = $('.CodeMirror-scroll');\n");
      out.write("                 editorDiv.height('100%');\n");
      out.write("                 editorDiv.width('100%');\n");
      out.write("\n");
      out.write("                 net.apachegui.Main.getInstance().init('Configuration-' + net.apachegui.Util.getQueryParam('file'));\n");
      out.write("\n");
      out.write("                 dom.byId(\"configurationBody\").style.visibility='visible';\n");
      out.write("             });\n");
      out.write("         });\n");
      out.write("    </script>\n");
      out.write("</head>\n");
      out.write("<body class=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${theme}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
      out.write(" editor\" id=\"configurationBody\" style=\"visibility:hidden\" >\n");
      out.write("\n");
      out.write("    ");
      org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, "/jsp/Init.jsp", out, true);
      out.write("\n");
      out.write("\n");
      out.write("    ");
      org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, "/jsp/configuration_tree/Dialogs.jsp", out, true);
      out.write("\n");
      out.write("\n");
      out.write("    <div id=\"appLayout\" class=\"demoLayout\" data-dojo-type=\"dijit.layout.BorderContainer\" data-dojo-props=\"design: 'headline'\">\n");
      out.write("\n");
      out.write("        ");
      org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, "/jsp/Heading.jsp", out, true);
      out.write("\n");
      out.write("\n");
      out.write("        ");
      org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, "/jsp/Menu.jsp", out, true);
      out.write("\n");
      out.write("\n");
      out.write("        <div id=\"centerPanel\" class=\"centerPanel\" data-dojo-type=\"dijit/layout/ContentPane\" data-dojo-props=\"region: 'center'\">\n");
      out.write("            <div data-dojo-type=\"dijit/layout/TabContainer\" style=\"width: 100%; height: 100%;\" id=\"configurationTabs\">\n");
      out.write("\n");
      out.write("                <div data-dojo-type=\"dijit/layout/ContentPane\" title=\"Editor View\" id=\"editorTab\">\n");
      out.write("\n");
      out.write("                    <div class=\"centerPanel\" data-dojo-type=\"dijit/layout/BorderContainer\" data-dojo-props=\"region: 'center', tabPosition: 'top'\">\n");
      out.write("\n");
      out.write("                        ");
      org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, "/jsp/editor/EditorMenu.jsp" + "?" + org.apache.jasper.runtime.JspRuntimeLibrary.URLEncode("option", request.getCharacterEncoding())+ "=" + org.apache.jasper.runtime.JspRuntimeLibrary.URLEncode("Configuration", request.getCharacterEncoding()), out, true);
      out.write("\n");
      out.write("\n");
      out.write("                        <div id=\"pane2\" class=\"centerPanel\" data-dojo-type=\"dijit.layout.ContentPane\" data-dojo-props=\"region: 'center', title:'Edit'\" >\n");
      out.write("                            <div id=\"fileform\"><textarea id=\"fileTextArea\" name=\"fileTextArea\">Loading File...</textarea></div>\n");
      out.write("                        </div>\n");
      out.write("                    </div>\n");
      out.write("\n");
      out.write("                </div>\n");
      out.write("\n");
      out.write("                <div data-dojo-type=\"dijit/layout/ContentPane\" title=\"Tree View\" id=\"treeTab\">\n");
      out.write("\n");
      out.write("                    <div class=\"centerPanel\" data-dojo-type=\"dijit/layout/BorderContainer\" data-dojo-props=\"region: 'center', tabPosition: 'top'\">\n");
      out.write("                        <div class=\"centerPanel\" data-dojo-type=\"dijit/layout/ContentPane\" data-dojo-props=\"region: 'top'\">\n");
      out.write("\n");
      out.write("                            ");
      org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, "/jsp/configuration_tree/Legend.jsp", out, true);
      out.write("<span><strong>File</strong>: ");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${filePath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
      out.write("</span>\n");
      out.write("\n");
      out.write("                        </div>\n");
      out.write("\n");
      out.write("                        <div class=\"centerPanel\" data-dojo-type=\"dijit/layout/ContentPane\" data-dojo-props=\"region: 'center'\">\n");
      out.write("                            <div class=\"tree_container\" id=\"configuration_tree_container\">\n");
      out.write("\n");
      out.write("                            </div>\n");
      out.write("                        </div>\n");
      out.write("                    </div>\n");
      out.write("\n");
      out.write("                </div>\n");
      out.write("\n");
      out.write("            </div>\n");
      out.write("        </div>\n");
      out.write("    </div>\n");
      out.write("\n");
      out.write("</body>\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try { out.clearBuffer(); } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
