//>>built
define("net/apachegui/globalsettings/Mime","dojo/_base/declare dojo/dom dijit/registry dojo/on dojo/request dojo/_base/array dojo/data/ItemFileWriteStore".split(" "),function(m,l,a,b,h,k,n){m("net.apachegui.globalsettings.Mime",null,{initialized:!1,currentGlobalAddedMimesMenuId:null,init:function(){!1===this.initialized&&(this.addListeners(),this.bindAddedMimesMenu(),this.initialized=!0)},setCurrentGlobalAddedMimesMenuId:function(a){this.currentGlobalAddedMimesMenuId=a.toString()},bindAddedMimesMenu:function(){a.byId("added_mimes_menu").bindDomNode(globalAddedMimesGrid.domNode)},
resetAddedMimesGrid:function(){globalAddedMimesGridStore=new n({url:"../web/Mime?option\x3daddedMimes",urlPreventCache:!0});globalAddedMimesGrid.setStore(globalAddedMimesGridStore)},addListeners:function(){var f=this;b(a.byId("searchServerMimeTypeButton"),"click",function(){var c=a.byId("searchServerMimeTypeInput").get("value").trim();""==c?net.apachegui.Util.alert("Error","You must enter a search term"):globalServerMimesGrid.filter({type:"*"+c+"*"})});b(a.byId("searchServerMimeExtensionsButton"),
"click",function(){var c=a.byId("searchServerMimeExtensionsInput").get("value").trim();""==c?net.apachegui.Util.alert("Error","You must enter a search term"):globalServerMimesGrid.filter({extensions:"*"+c+"*"})});b(a.byId("searchServerMimeResetButton"),"click",function(){globalServerMimesGrid.filter({type:"*"});a.byId("searchServerMimeTypeInput").reset();a.byId("searchServerMimeExtensionsInput").reset()});globalAddedMimesGrid.onRowContextMenu=function(a){var d=globalAddedMimesGrid.getItem(a.rowIndex);
k.forEach(globalAddedMimesGrid.store.getAttributes(d),function(a){var c=globalAddedMimesGrid.store.getValues(d,a);"id"==a&&f.setCurrentGlobalAddedMimesMenuId(c)})};b(a.byId("addMimeMenuItem"),"click",function(){a.byId("addMimeDialog").show()});b(a.byId("addMimeCloseButton"),"click",function(){a.byId("addMimeDialog").hide()});b(a.byId("addMimeSubmitButton"),"click",function(){var c=a.byId("addMimeType").get("value").trim(),d=a.byId("addMimeExtensions").get("value").trim();if(""==c)net.apachegui.Util.alert("Error",
"You must specify a type");else if(""==d)net.apachegui.Util.alert("Error","You must specify an extension");else{var e=net.apachegui.Util.noCloseDialog("Adding","Please Wait...");e.show();h.post("../web/Mime",{data:{option:"addMime",type:c,extensions:d},handleAs:"json",sync:!1}).response.then(function(c){f.resetAddedMimesGrid();a.byId("addMimeDialog").hide();a.byId("addMimeType").reset();a.byId("addMimeExtensions").reset();e.remove()},function(a){e.remove();net.apachegui.Util.alert("Error",a.response.data.message)})}});
b(a.byId("editMimeMenuItem"),"click",function(){var c="",d="",e=globalAddedMimesGrid.getItem(f.currentGlobalAddedMimesMenuId);k.forEach(globalAddedMimesGrid.store.getAttributes(e),function(a){var b=globalAddedMimesGrid.store.getValues(e,a);"type"==a&&(c=b);"extensions"==a&&(d=b)});l.byId("editMimeType").innerHTML=c;a.byId("editMimeExtensions").set("value",d);a.byId("editMimeDialog").show()});b(a.byId("editMimeCloseButton"),"click",function(){a.byId("editMimeDialog").hide()});b(a.byId("editMimeSubmitButton"),
"click",function(){var c=l.byId("editMimeType").innerHTML.trim(),d=a.byId("editMimeExtensions").get("value").trim();if(""==c)net.apachegui.Util.alert("Error","You must specify a type");else if(""==d)net.apachegui.Util.alert("Error","You must specify an extension");else{var b=net.apachegui.Util.noCloseDialog("Updating","Please Wait...");b.show();h.post("../web/Mime",{data:{option:"editMime",type:c,extensions:d},handleAs:"json",sync:!1}).response.then(function(c){f.resetAddedMimesGrid();a.byId("editMimeDialog").hide();
b.remove()},function(a){b.remove();net.apachegui.Util.alert("Error",a.response.data.message)})}});b(a.byId("removeMimeMenuItem"),"click",function(){var a="",b="",e=globalAddedMimesGrid.getItem(f.currentGlobalAddedMimesMenuId);k.forEach(globalAddedMimesGrid.store.getAttributes(e),function(f){var g=globalAddedMimesGrid.store.getValues(e,f);"type"==f&&(a=g);"extensions"==f&&(b=g)});net.apachegui.Util.confirmDialog("Please Confirm","Are you sure you want to delete the follwing MIME?\x3cbr/\x3e\x3cstrong\x3eType\x3c/strong\x3e: "+
a+"\x3cbr/\x3e\x3cstrong\x3eExtensions\x3c/strong\x3e: "+b+"\x3cbr/\x3e",function(e){if(e){var g=net.apachegui.Util.noCloseDialog("Deleting","Please Wait...");g.show();h.post("../web/Mime",{data:{option:"removeMime",type:a,extensions:b},handleAs:"json",sync:!1}).response.then(function(a){f.resetAddedMimesGrid();g.remove()},function(a){g.remove();net.apachegui.Util.alert("Error",a.response.data.message)})}})})}});net.apachegui.Util.setupSingletonInstance(net.apachegui.globalsettings.Mime)});