//>>built
define("net/apachegui/globalsettings/Modules","dojo/_base/declare dojo/dom dijit/registry dojo/on dojo/request dojo/_base/array dojo/data/ItemFileWriteStore".split(" "),function(l,m,c,e,g,h,k){l("net.apachegui.globalsettings.Modules",null,{currentSharedModulesMenuId:"",currentSharedModulesRow:"",markedSharedModules:[],currentAvailableModulesMenuId:"",currentAvailableModulesRow:"",initialized:!1,init:function(){!1===this.initialized&&(c.byId("sharedModules_menu").bindDomNode(sharedModulesGrid.domNode),
c.byId("availableModules_menu").bindDomNode(availableModulesGrid.domNode),this.addListeners(),this.initialized=!0)},setCurrentSharedModulesMenuId:function(a){this.currentSharedModulesMenuId=a.toString()},setCurrentSharedModulesRow:function(a){this.currentSharedModulesRow=a},getMarkedSharedModules:function(){return this.markedSharedModules},getMarkedAvailableModules:function(){return this.markedAvailableModules},markForRemoval:function(){-1==this.markedSharedModules.indexOf(this.currentSharedModulesMenuId)&&
this.markedSharedModules.push(this.currentSharedModulesMenuId);sharedModulesStore.setValue(sharedModulesGrid.getItem(this.currentSharedModulesRow),"status","Marked For Removal");sharedModulesStore.isDirty()&&sharedModulesStore.save()},removeSharedModules:function(){for(var a=this,b={option:"removeSharedModules",sharedModules:""},d=0,d=0;d<this.markedSharedModules.length;d++)b.sharedModules+=this.markedSharedModules[d],d!=this.markedSharedModules.length-1&&(b.sharedModules+=":");var f=net.apachegui.Util.noCloseDialog("Updating",
"Please Wait...");f.show();g.post("../web/Modules",{data:b,handleAs:"json",sync:!1}).response.then(function(b){a.refreshAll();f.remove()},function(a){f.remove();net.apachegui.Util.alert("Error",a.response.data.message)})},refreshSharedModules:function(){sharedModulesStore=new k({url:"../web/Modules?option\x3dshared",urlPreventCache:!0});sharedModulesGrid.setStore(sharedModulesStore);this.markedSharedModules=[]},setCurrentAvailableModulesMenuId:function(a){this.currentAvailableModulesMenuId=a.toString()},
setCurrentAvailableModulesRow:function(a){this.currentAvailableModulesRow=a},showLoadDirective:function(){var a=net.apachegui.Util.noCloseDialog("Loading","Please Wait...");a.show();g.get("../web/Modules",{query:{option:"getLoadDirective",name:this.currentAvailableModulesMenuId},handleAs:"json",sync:!1,preventCache:!0}).response.then(function(b){net.apachegui.Util.alert("Load Directive",'To use this module add the following directive to your apache configuration:\x3cbr/\x3e\x3cspan style\x3d"font-weight:bold;"\x3e'+
b.data.directive+"\x3c/span\x3e");a.remove()},function(b){a.remove();net.apachegui.Util.alert("Error",b.response.data.message)})},refreshAvailableModules:function(){availableModulesStore=new k({url:"../web/Modules?option\x3davailable",urlPreventCache:!0});availableModulesGrid.setStore(availableModulesStore);this.markedAvailableModules=[]},refreshAll:function(){this.refreshSharedModules();this.refreshAvailableModules()},addListeners:function(){var a=this;e(c.byId("sharedModulesMenuItem"),"click",function(){a.markForRemoval()});
e(c.byId("availableModulesMenuItem"),"click",function(){a.showLoadDirective()});e(c.byId("removalButton"),"click",function(){0==a.getMarkedSharedModules().length?net.apachegui.Util.alert("Nothing Selected",'You have not selected any shared modules for removal.\x3cbr/\x3eTo select a module right click and select "Mark For Removal".'):net.apachegui.Util.confirmDialog("Please Confirm","Are you sure you want to remove all marked modules?",function(b){b&&a.removeSharedModules()})});e(c.byId("resetRemovalButton"),
"click",function(){a.refreshSharedModules()});sharedModulesGrid.onRowContextMenu=function(b){var d=sharedModulesGrid.getItem(b.rowIndex);a.setCurrentSharedModulesRow(b.rowIndex);h.forEach(sharedModulesGrid.store.getAttributes(d),function(b){var c=sharedModulesGrid.store.getValues(d,b);"id"==b&&a.setCurrentSharedModulesMenuId(c)})};e(c.byId("resetAvailableButton"),"click",function(){a.refreshAvailableModules()});availableModulesGrid.onRowContextMenu=function(b){var d=availableModulesGrid.getItem(b.rowIndex);
a.setCurrentAvailableModulesRow(b.rowIndex);h.forEach(availableModulesGrid.store.getAttributes(d),function(b){var c=availableModulesGrid.store.getValues(d,b);"id"==b&&a.setCurrentAvailableModulesMenuId(c)})}}});net.apachegui.Util.setupSingletonInstance(net.apachegui.globalsettings.Modules)});